/**
 * Database schema definitions
 *
 * Drizzle ORM schema for PostgreSQL including tables for
 * catalog items, users, tags, MCP servers, and related entities.
 */
import { pgTable, text, timestamp, pgEnum, integer, bigint, boolean, primaryKey, jsonb, index, uniqueIndex, halfvec, real, numeric } from 'drizzle-orm/pg-core'
import { relations, sql } from 'drizzle-orm'

export const itemTypeEnum = pgEnum('item_type', [
  'skill',
  'agent',
  'command',
  'guide',
  'hook',
  'package',
])

export const difficultyEnum = pgEnum('difficulty', ['easy', 'medium', 'hard'])

// User roles for RBAC
export const userRoleEnum = pgEnum('user_role', ['super_admin', 'admin', 'editor', 'viewer'])

/** 로그인 계정 상태 — 개인정보 삭제와 접근 차단을 구분한다 */
export const userAccountStatusEnum = pgEnum('user_account_status', ['active', 'suspended'])

/**
 * Organization role enum for organization memberships
 */
export const orgRoleEnum = pgEnum('org_role', ['org_admin', 'org_editor', 'org_viewer'])

/** 조직 소속 상태 — 퇴사 이력을 지우지 않고 현재 구성원 여부를 표현한다 */
export const orgMembershipStatusEnum = pgEnum('org_membership_status', ['active', 'offboarded'])

/**
 * Visibility enum for catalog items
 */
export const visibilityEnum = pgEnum('visibility', ['private', 'public'])

/**
 * Invitation status enum for organization invitations
 */
export const orgInvitationStatusEnum = pgEnum('org_invitation_status', ['pending', 'accepted', 'rejected', 'expired'])

export const catalogItems = pgTable('catalog_items', {
  id: text('id').primaryKey(),
  type: itemTypeEnum('type').notNull(),
  name: text('name').notNull(),
  description: text('description').notNull().default(''),
  authorId: text('author_id').references(() => users.id), // FK to users table
  tags: text('tags').array().default([]),

  difficulty: difficultyEnum('difficulty'),
  pluginId: text('plugin_id'),
  estimatedTime: text('estimated_time'),
  dependencies: text('dependencies').array().default([]), // e.g., ["mcp:github", "skill:git-commit"]
  // Platform compatibility (null = all platforms)
  platforms: text('platforms').array(),
  likes: integer('likes').notNull().default(0),
  content: text('content').notNull(),
  readme: text('readme'),
  // Additional files (scripts, references, etc.) - JSON array of {name, content, type?}
  files: jsonb('files').$type<Array<{ name: string; content: string; type?: string }>>(),

  // Type-specific fields for Claude Code plugins
  // Skill & Command & Agent: allowed tools (comma-separated, e.g., "Read, Grep, Bash")
  allowedTools: text('allowed_tools'),
  // Agent-specific fields
  agentModel: text('agent_model'), // sonnet | opus | haiku | inherit
  agentPermissionMode: text('agent_permission_mode'), // default | acceptEdits | bypassPermissions | plan | ignore
  agentSkills: text('agent_skills'), // comma-separated skill names to load
  // Command-specific fields
  commandArgumentHint: text('command_argument_hint'), // e.g., "[message]"
  commandDisableModelInvocation: boolean('command_disable_model_invocation').default(false),

  // Hook-specific fields
  hookEvent: text('hook_event'), // PreCompact, SessionStart, PreToolUse, PostToolUse, etc.
  hookMatcher: text('hook_matcher'), // auto, manual, startup, resume, compact, tool name, etc.
  hookCommand: text('hook_command'), // Shell command to execute
  hookTimeout: integer('hook_timeout'), // Timeout in milliseconds
  hookBlocking: boolean('hook_blocking').default(true), // Whether hook blocks execution

  // MCP integration field
  mcpEnabled: boolean('mcp_enabled').default(false),

  // Version management
  version: text('version').default('1.0.0'),
  status: text('status').default('published'), // 'draft' | 'published'
  changelog: text('changelog'), // Latest version changelog

  // Vector embedding for semantic search (1536 dimensions for OpenAI text-embedding-3-small)
  embedding: halfvec('embedding', { dimensions: 3072 }),

  // Multi-tenancy & collaboration fields
  /** Organization owner (nullable for migration compatibility) */
  orgId: text('org_id').references(() => organizations.id),
  /** Visibility level (private or public) */
  visibility: visibilityEnum('visibility').default('public'),
  /** Self-reference to original item if this is a fork (stored as text to avoid circular type dependency) */
  forkedFrom: text('forked_from'),
  /** Count of times this item has been forked */
  forkCount: integer('fork_count').notNull().default(0),

  /** External source repo (e.g., "anthropics/skills") for imported skills */
  sourceRepo: text('source_repo'),
  /** Commit SHA from source repo for update detection */
  sourceCommitSha: text('source_commit_sha'),

  /** Whether this item was auto-generated by the EvoSkill pipeline */
  evoGenerated: boolean('evo_generated').default(false),
  /** FK to evo_failure_patterns.id that triggered creation */
  evoPatternId: text('evo_pattern_id'),

  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
}, (table) => [
  index('catalog_items_type_idx').on(table.type),
  index('catalog_items_status_idx').on(table.status),
  index('catalog_items_author_id_idx').on(table.authorId),
  index('catalog_items_mcp_enabled_idx').on(table.mcpEnabled),
  index('catalog_items_type_status_idx').on(table.type, table.status),
  index('catalog_items_org_id_idx').on(table.orgId),
  index('catalog_items_visibility_idx').on(table.visibility),
  index('catalog_items_forked_from_idx').on(table.forkedFrom),
])

export type CatalogItemRecord = typeof catalogItems.$inferSelect
export type NewCatalogItemRecord = typeof catalogItems.$inferInsert

// ============================================
// Catalog Item Translations Table (i18n)
// ============================================

/**
 * Translations for catalog items
 *
 * Stores locale-specific translations for catalog item text fields.
 * Falls back to the original catalog_items data when no translation exists.
 */
export const catalogItemTranslations = pgTable('catalog_item_translations', {
  /** Reference to the catalog item */
  itemId: text('item_id').notNull().references(() => catalogItems.id, { onDelete: 'cascade' }),
  /** Locale code (e.g., 'ko', 'en') */
  locale: text('locale').notNull(),
  /** Translated item name */
  name: text('name'),
  /** Translated description */
  description: text('description'),
  /** Translated content (main body) */
  content: text('content'),
  /** Translated README */
  readme: text('readme'),
  /** Whether this translation was auto-generated */
  isAutoTranslated: boolean('is_auto_translated').default(false),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
}, (table) => [
  primaryKey({ columns: [table.itemId, table.locale] }),
  index('catalog_item_translations_locale_idx').on(table.locale),
])

export type CatalogItemTranslationRecord = typeof catalogItemTranslations.$inferSelect
export type NewCatalogItemTranslationRecord = typeof catalogItemTranslations.$inferInsert

// ============================================
// Users Table (OAuth)
// ============================================

export const users = pgTable('users', {
  id: text('id').primaryKey(), // Google sub ID
  email: text('email').notNull().unique(),
  name: text('name'),
  image: text('image'),
  role: userRoleEnum('role').notNull().default('viewer'),
  /** 서비스 전체 로그인 가능 여부. 퇴사·보안 차단은 suspended로 남긴다 */
  accountStatus: userAccountStatusEnum('account_status').notNull().default('active'),
  deactivatedAt: timestamp('deactivated_at', { withTimezone: true }),
  deactivationReason: text('deactivation_reason'),
  ronaUserId: text('rona_user_id'),
  lastLoginAt: timestamp('last_login_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
})

export type UserRecord = typeof users.$inferSelect
export type NewUserRecord = typeof users.$inferInsert

// ============================================
// Organizations & Memberships
// ============================================

/**
 * Organizations table for multi-tenancy
 */
export const organizations = pgTable('organizations', {
  id: text('id').primaryKey().$defaultFn(() => crypto.randomUUID()),
  /** Organization name */
  name: text('name').notNull(),
  /** URL-safe slug for organization */
  slug: text('slug').notNull().unique(),
  /** Email domains allowed to auto-join (e.g., ["gpters.org"]) */
  allowedDomains: jsonb('allowed_domains').$type<string[]>().notNull().default([]),
  /** Organization description */
  description: text('description'),
  /** Whether organization is active */
  isActive: boolean('is_active').notNull().default(true),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
})

export type OrganizationRecord = typeof organizations.$inferSelect
export type NewOrganizationRecord = typeof organizations.$inferInsert

/**
 * Organization memberships junction table (users ↔ organizations)
 */
export const orgMemberships = pgTable('org_memberships', {
  userId: text('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  orgId: text('org_id').notNull().references(() => organizations.id, { onDelete: 'cascade' }),
  /** Member role within organization */
  role: orgRoleEnum('role').notNull().default('org_viewer'),
  /** 현재 소속 여부. offboarded 행도 감사·과거 집계를 위해 보존한다 */
  status: orgMembershipStatusEnum('status').notNull().default('active'),
  /** When user joined organization */
  joinedAt: timestamp('joined_at', { withTimezone: true }).defaultNow(),
  /** 조직 소속 종료 시각 */
  endedAt: timestamp('ended_at', { withTimezone: true }),
  /** 소속 종료를 처리한 사용자 */
  deactivatedBy: text('deactivated_by').references(() => users.id, { onDelete: 'set null' }),
  deactivationReason: text('deactivation_reason'),
  /** User who invited this member */
  invitedBy: text('invited_by').references(() => users.id, { onDelete: 'set null' }),
}, (table) => [
  primaryKey({ columns: [table.userId, table.orgId] }),
  index('org_memberships_user_id_idx').on(table.userId),
  index('org_memberships_org_id_idx').on(table.orgId),
  index('org_memberships_org_status_idx').on(table.orgId, table.status),
])

export type OrgMembershipRecord = typeof orgMemberships.$inferSelect
export type NewOrgMembershipRecord = typeof orgMemberships.$inferInsert

/**
 * Organization invitations table
 */
export const orgInvitations = pgTable('org_invitations', {
  id: text('id').primaryKey().$defaultFn(() => crypto.randomUUID()),
  /** Organization to join */
  orgId: text('org_id').notNull().references(() => organizations.id, { onDelete: 'cascade' }),
  /** Invitee email address */
  email: text('email').notNull(),
  /** Role to assign upon acceptance */
  role: orgRoleEnum('role').notNull().default('org_viewer'),
  /** Invitation status */
  status: orgInvitationStatusEnum('status').notNull().default('pending'),
  /** User who sent invitation */
  invitedBy: text('invited_by').references(() => users.id, { onDelete: 'set null' }),
  /** Invitation expiration timestamp */
  expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
}, (table) => [
  index('org_invitations_email_org_status_idx').on(table.email, table.orgId, table.status),
  index('org_invitations_org_id_idx').on(table.orgId),
])

export type OrgInvitationRecord = typeof orgInvitations.$inferSelect
export type NewOrgInvitationRecord = typeof orgInvitations.$inferInsert

// ============================================
// Normalized Tables
// ============================================

// Tags table
export const tags = pgTable('tags', {
  id: text('id').primaryKey(), // slug-style id (e.g., "writing", "code")
  label: text('label').notNull(), // Display label (e.g., "문서 작성", "코드")
  color: text('color').notNull().default('bg-gray-100 text-gray-800'),
  description: text('description'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
})

export type TagRecord = typeof tags.$inferSelect
export type NewTagRecord = typeof tags.$inferInsert

// MCP Servers table
export const mcpServers = pgTable('mcp_servers', {
  id: text('id').primaryKey(), // slug-style id (e.g., "github", "slack")
  label: text('label').notNull(), // Display label (e.g., "GitHub MCP")
  description: text('description').notNull().default(''),
  documentationUrl: text('documentation_url'),
  /** CLI install command (e.g., "claude mcp add github -- npx @modelcontextprotocol/server-github") */
  installCommand: text('install_command'),
  /** npm package name (e.g., "@modelcontextprotocol/server-github") */
  npmPackage: text('npm_package'),
  /** GitHub repository (e.g., "modelcontextprotocol/servers") */
  githubRepo: text('github_repo'),
  /** Supported platforms (e.g., ["claude-code", "cursor", "opencode"]) */
  platforms: text('platforms').array(),
  /** Use case scenarios (e.g., ["코드 리뷰", "PR 생성"]) */
  useCases: text('use_cases').array(),
  /** Alternative approach when MCP is unavailable */
  fallbackApproach: text('fallback_approach'),
  /** Vector embedding for semantic search (3072 dimensions, text-embedding-3-large) */
  embedding: halfvec('embedding', { dimensions: 3072 }),
  /** Last sync timestamp for automated updates */
  lastSyncedAt: timestamp('last_synced_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
})

export type McpServerRecord = typeof mcpServers.$inferSelect
export type NewMcpServerRecord = typeof mcpServers.$inferInsert

// CLI Tools table — exercise-aware CLI tool recommendations (DEV-3062)
export const cliTools = pgTable('cli_tools', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  /** CLI install command (e.g., "npm install -g vercel") */
  installCommand: text('install_command').notNull(),
  latestVersion: text('latest_version'),
  npmPackage: text('npm_package'),
  /** Version sync source (e.g., "npm", "pypi", "github") */
  syncSource: text('sync_source').default('npm'),
  /** Context7 library ID for version tracking (e.g., "/vercel/next.js") */
  context7LibraryId: text('context7_library_id'),
  /** Related tags for techStack matching */
  relatedTags: text('related_tags').array(),
  /** Priority tier: 1=essential, 2=common, 3=general */
  tier: integer('tier').default(3),
  /** chub document ID for SDK docs sync (e.g., "openai/chat") */
  chubDocId: text('chub_doc_id'),
  /** chub language for docs fetch (e.g., "javascript", "python") */
  chubLang: text('chub_lang').default('javascript'),
  /** Raw SDK documentation from chub (markdown) */
  rawDocs: text('raw_docs'),
  /** SHA-256 hash of rawDocs for change detection */
  rawDocsHash: text('raw_docs_hash'),
  /** Vector embedding for semantic search (3072 dimensions, text-embedding-3-large) */
  embedding: halfvec('embedding', { dimensions: 3072 }),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
})

export type CliToolRecord = typeof cliTools.$inferSelect
export type NewCliToolRecord = typeof cliTools.$inferInsert

// Junction table for catalog items <-> tags (many-to-many)
export const catalogItemTags = pgTable('catalog_item_tags', {
  itemId: text('item_id').notNull().references(() => catalogItems.id, { onDelete: 'cascade' }),
  tagId: text('tag_id').notNull().references(() => tags.id, { onDelete: 'cascade' }),
}, (table) => [
  primaryKey({ columns: [table.itemId, table.tagId] }),
])

export type CatalogItemTagRecord = typeof catalogItemTags.$inferSelect
export type NewCatalogItemTagRecord = typeof catalogItemTags.$inferInsert

// Junction table for packages <-> items (many-to-many)
// A package can contain multiple items, and an item can belong to multiple packages
export const packageItems = pgTable('package_items', {
  packageId: text('package_id').notNull().references(() => catalogItems.id, { onDelete: 'cascade' }),
  itemId: text('item_id').notNull().references(() => catalogItems.id, { onDelete: 'cascade' }),
  displayOrder: integer('display_order').notNull().default(0),
}, (table) => [
  primaryKey({ columns: [table.packageId, table.itemId] }),
  index('package_items_package_id_idx').on(table.packageId),
  index('package_items_item_id_idx').on(table.itemId),
])

export type PackageItemRecord = typeof packageItems.$inferSelect
export type NewPackageItemRecord = typeof packageItems.$inferInsert

// ============================================
// Relations
// ============================================

export const catalogItemsRelations = relations(catalogItems, ({ one, many }) => ({
  itemTags: many(catalogItemTags),
  translations: many(catalogItemTranslations),
  // Package relations
  packageContents: many(packageItems, { relationName: 'packageContents' }), // Items contained in this package
  containedInPackages: many(packageItems, { relationName: 'containedInPackages' }), // Packages containing this item
  // Organization relation
  organization: one(organizations, {
    fields: [catalogItems.orgId],
    references: [organizations.id],
  }),
}))

export const catalogItemTranslationsRelations = relations(catalogItemTranslations, ({ one }) => ({
  item: one(catalogItems, {
    fields: [catalogItemTranslations.itemId],
    references: [catalogItems.id],
  }),
}))

export const organizationsRelations = relations(organizations, ({ many }) => ({
  memberships: many(orgMemberships),
  invitations: many(orgInvitations),
  catalogItems: many(catalogItems),
}))

export const orgMembershipsRelations = relations(orgMemberships, ({ one }) => ({
  organization: one(organizations, {
    fields: [orgMemberships.orgId],
    references: [organizations.id],
  }),
  user: one(users, {
    fields: [orgMemberships.userId],
    references: [users.id],
  }),
  inviter: one(users, {
    fields: [orgMemberships.invitedBy],
    references: [users.id],
  }),
}))

export const orgInvitationsRelations = relations(orgInvitations, ({ one }) => ({
  organization: one(organizations, {
    fields: [orgInvitations.orgId],
    references: [organizations.id],
  }),
  inviter: one(users, {
    fields: [orgInvitations.invitedBy],
    references: [users.id],
  }),
}))

export const usersRelations = relations(users, ({ many }) => ({
  orgMemberships: many(orgMemberships),
}))

export const tagsRelations = relations(tags, ({ many }) => ({
  itemTags: many(catalogItemTags),
}))

export const catalogItemTagsRelations = relations(catalogItemTags, ({ one }) => ({
  item: one(catalogItems, {
    fields: [catalogItemTags.itemId],
    references: [catalogItems.id],
  }),
  tag: one(tags, {
    fields: [catalogItemTags.tagId],
    references: [tags.id],
  }),
}))

export const packageItemsRelations = relations(packageItems, ({ one }) => ({
  package: one(catalogItems, {
    fields: [packageItems.packageId],
    references: [catalogItems.id],
    relationName: 'packageContents',
  }),
  item: one(catalogItems, {
    fields: [packageItems.itemId],
    references: [catalogItems.id],
    relationName: 'containedInPackages',
  }),
}))

// ============================================
// OAuth 2.1 Tables (for MCP native auth)
// ============================================

// OAuth Clients - Dynamic Client Registration (RFC 7591)
export const oauthClients = pgTable('oauth_clients', {
  id: text('id').primaryKey(), // client_id (UUID)
  secretHash: text('secret_hash'), // SHA-256 hash of client_secret (null for public clients)
  name: text('name').notNull(),
  redirectUris: jsonb('redirect_uris').$type<string[]>().notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
})

export type OAuthClientRecord = typeof oauthClients.$inferSelect
export type NewOAuthClientRecord = typeof oauthClients.$inferInsert

// OAuth Authorization Codes - PKCE required
export const oauthCodes = pgTable('oauth_codes', {
  code: text('code').primaryKey(), // Authorization code (UUID)
  clientId: text('client_id').notNull().references(() => oauthClients.id, { onDelete: 'cascade' }),
  userId: text('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  codeChallenge: text('code_challenge').notNull(), // PKCE code_challenge
  codeChallengeMethod: text('code_challenge_method').notNull().default('S256'), // S256 only
  redirectUri: text('redirect_uri').notNull(),
  scope: text('scope'), // Optional scopes
  expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
}, (table) => [
  index('oauth_codes_client_id_idx').on(table.clientId),
  index('oauth_codes_user_id_idx').on(table.userId),
  index('oauth_codes_expires_at_idx').on(table.expiresAt),
])

export type OAuthCodeRecord = typeof oauthCodes.$inferSelect
export type NewOAuthCodeRecord = typeof oauthCodes.$inferInsert

// OAuth Access Tokens - Issued after successful OAuth flow
export const oauthAccessTokens = pgTable('oauth_access_tokens', {
  id: text('id').primaryKey().$defaultFn(() => crypto.randomUUID()),
  tokenHash: text('token_hash').notNull().unique(), // SHA-256 hash of token
  clientId: text('client_id').notNull().references(() => oauthClients.id, { onDelete: 'cascade' }),
  userId: text('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  name: text('name'), // User-facing label for API key management
  scope: text('scope'), // Optional scopes
  expiresAt: timestamp('expires_at', { withTimezone: true }),
  lastUsedAt: timestamp('last_used_at', { withTimezone: true }),
  usageCount: integer('usage_count').notNull().default(0),
  isActive: boolean('is_active').notNull().default(true),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
}, (table) => [
  index('oauth_access_tokens_token_hash_idx').on(table.tokenHash),
  index('oauth_access_tokens_user_id_idx').on(table.userId),
  index('oauth_access_tokens_client_id_idx').on(table.clientId),
])

export type OAuthAccessTokenRecord = typeof oauthAccessTokens.$inferSelect
export type NewOAuthAccessTokenRecord = typeof oauthAccessTokens.$inferInsert

// OAuth Refresh Tokens - Issued alongside access tokens for token rotation
export const oauthRefreshTokens = pgTable('oauth_refresh_tokens', {
  id: text('id').primaryKey().$defaultFn(() => crypto.randomUUID()),
  tokenHash: text('token_hash').notNull().unique(), // SHA-256 hash of refresh token
  clientId: text('client_id').notNull().references(() => oauthClients.id, { onDelete: 'cascade' }),
  userId: text('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  accessTokenId: text('access_token_id').references(() => oauthAccessTokens.id, { onDelete: 'set null' }),
  scope: text('scope'),
  /** Token chain identifier — all tokens from the same auth code share a familyId */
  familyId: text('family_id').notNull(),
  /** Rotation counter within the family (starts at 0) */
  generation: integer('generation').notNull().default(0),
  expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
  isActive: boolean('is_active').notNull().default(true),
  revokedAt: timestamp('revoked_at', { withTimezone: true }),
  revokeReason: text('revoke_reason'), // 'rotated' | 'user_logout' | 'replay_detected' | 'manual'
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
}, (table) => [
  index('oauth_refresh_tokens_token_hash_idx').on(table.tokenHash),
  index('oauth_refresh_tokens_user_id_idx').on(table.userId),
  index('oauth_refresh_tokens_client_id_idx').on(table.clientId),
  index('oauth_refresh_tokens_family_id_idx').on(table.familyId),
  index('oauth_refresh_tokens_expires_at_idx').on(table.expiresAt),
])

export type OAuthRefreshTokenRecord = typeof oauthRefreshTokens.$inferSelect
export type NewOAuthRefreshTokenRecord = typeof oauthRefreshTokens.$inferInsert

// Relations for OAuth tables
export const oauthClientsRelations = relations(oauthClients, ({ many }) => ({
  codes: many(oauthCodes),
  accessTokens: many(oauthAccessTokens),
  refreshTokens: many(oauthRefreshTokens),
}))

export const oauthCodesRelations = relations(oauthCodes, ({ one }) => ({
  client: one(oauthClients, {
    fields: [oauthCodes.clientId],
    references: [oauthClients.id],
  }),
  user: one(users, {
    fields: [oauthCodes.userId],
    references: [users.id],
  }),
}))

export const oauthAccessTokensRelations = relations(oauthAccessTokens, ({ one }) => ({
  client: one(oauthClients, {
    fields: [oauthAccessTokens.clientId],
    references: [oauthClients.id],
  }),
  user: one(users, {
    fields: [oauthAccessTokens.userId],
    references: [users.id],
  }),
}))

export const oauthRefreshTokensRelations = relations(oauthRefreshTokens, ({ one }) => ({
  client: one(oauthClients, {
    fields: [oauthRefreshTokens.clientId],
    references: [oauthClients.id],
  }),
  user: one(users, {
    fields: [oauthRefreshTokens.userId],
    references: [users.id],
  }),
  accessToken: one(oauthAccessTokens, {
    fields: [oauthRefreshTokens.accessTokenId],
    references: [oauthAccessTokens.id],
  }),
}))

// OAuth Device Codes - RFC 8628 Device Authorization Grant
export const deviceCodes = pgTable('device_codes', {
  id: text('id').primaryKey().$defaultFn(() => crypto.randomUUID()),
  deviceCode: text('device_code').notNull().unique(), // Opaque code for CLI polling
  userCode: text('user_code').notNull().unique(), // Human-readable "ABCD-1234"
  clientId: text('client_id').notNull().references(() => oauthClients.id, { onDelete: 'cascade' }),
  scope: text('scope'),
  userId: text('user_id').references(() => users.id, { onDelete: 'cascade' }), // Set on approval
  status: text('status').notNull().default('pending'), // pending | approved | denied | expired
  expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
  interval: integer('interval').notNull().default(5), // Polling interval in seconds
  lastPolledAt: timestamp('last_polled_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
}, (table) => [
  index('device_codes_device_code_idx').on(table.deviceCode),
  index('device_codes_user_code_idx').on(table.userCode),
  index('device_codes_expires_at_idx').on(table.expiresAt),
])

export type DeviceCodeRecord = typeof deviceCodes.$inferSelect
export type NewDeviceCodeRecord = typeof deviceCodes.$inferInsert

export const deviceCodesRelations = relations(deviceCodes, ({ one }) => ({
  client: one(oauthClients, {
    fields: [deviceCodes.clientId],
    references: [oauthClients.id],
  }),
  user: one(users, {
    fields: [deviceCodes.userId],
    references: [users.id],
  }),
}))

// ============================================
// Item Version History Table
// ============================================

export const versionTypeEnum = pgEnum('version_type', ['major', 'minor', 'patch'])

// Suggestion status for collaboration workflow
export const suggestionStatusEnum = pgEnum('suggestion_status', ['pending', 'accepted', 'rejected'])

export const itemVersions = pgTable('item_versions', {
  id: text('id').primaryKey().$defaultFn(() => crypto.randomUUID()),
  itemId: text('item_id').notNull().references(() => catalogItems.id, { onDelete: 'cascade' }),
  version: text('version').notNull(), // semver format: "1.0.0"
  versionType: versionTypeEnum('version_type').notNull(), // major | minor | patch

  // Snapshot of the item at this version
  content: text('content').notNull(),
  changelog: text('changelog'), // What changed in this version

  // Metadata
  createdBy: text('created_by').references(() => users.id, { onDelete: 'set null' }),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),

  // Additional snapshot data for rollback
  snapshotData: jsonb('snapshot_data').$type<{
    name?: string
    description?: string
    allowedTools?: string
    dependencies?: string[]
    files?: Array<{ name: string; content: string; type?: string }>
    [key: string]: unknown
  }>(),
}, (table) => [
  index('item_versions_item_id_idx').on(table.itemId),
  index('item_versions_version_idx').on(table.version),
  index('item_versions_created_at_idx').on(table.createdAt),
])

export type ItemVersionRecord = typeof itemVersions.$inferSelect
export type NewItemVersionRecord = typeof itemVersions.$inferInsert

// Relations for item versions
export const itemVersionsRelations = relations(itemVersions, ({ one }) => ({
  item: one(catalogItems, {
    fields: [itemVersions.itemId],
    references: [catalogItems.id],
  }),
  createdByUser: one(users, {
    fields: [itemVersions.createdBy],
    references: [users.id],
  }),
}))

// ============================================
// MCP Audit Logs Table
// ============================================

export const mcpAuditLogs = pgTable('mcp_audit_logs', {
  id: text('id').primaryKey().$defaultFn(() => crypto.randomUUID()),

  // Request info
  method: text('method').notNull(), // JSON-RPC method or REST action (e.g., 'tools/call', 'search')
  tool: text('tool'), // Tool name if applicable (e.g., 'search_plugins', 'get_plugin_content')

  // Authentication (OAuth access token)
  accessTokenId: text('access_token_id').references(() => oauthAccessTokens.id, { onDelete: 'set null' }),
  isAuthenticated: boolean('is_authenticated').notNull().default(false),

  // Client info (masked for privacy)
  ipHash: text('ip_hash').notNull(), // SHA-256 hash of IP for privacy
  userAgent: text('user_agent'),
  clientType: text('client_type'),       // Resolved type: claude_code, opencode, cursor, web_browser, cli, unknown
  clientName: text('client_name'),       // Raw name from MCP initialize clientInfo
  clientVersion: text('client_version'), // Raw version from MCP initialize clientInfo

  // Request/Response
  requestParams: jsonb('request_params').$type<Record<string, unknown>>(), // Sanitized request params
  responseStatus: text('response_status').notNull(), // 'success' | 'error' | 'rate_limited'
  responseTime: integer('response_time'), // Response time in milliseconds
  errorCode: text('error_code'), // Error code if failed
  errorMessage: text('error_message'), // Error message if failed

  // Discovery analytics fields
  /** MCP session ID for linking search → view → install flow */
  sessionId: text('session_id'),
  /** Search result list snapshot [{itemId, rank, score}] */
  searchResults: jsonb('search_results').$type<Array<{ itemId: string; rank: number; score: number }>>(),
  /** How user arrived: 'search' | 'suggest' | 'direct' | 'browse' */
  referralSource: text('referral_source'),

  // Metadata
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  index('mcp_audit_logs_created_at_idx').on(table.createdAt),
  index('mcp_audit_logs_access_token_id_idx').on(table.accessTokenId),
  index('mcp_audit_logs_method_idx').on(table.method),
  index('mcp_audit_logs_response_status_idx').on(table.responseStatus),
  // Composite index for common queries
  index('mcp_audit_logs_created_status_idx').on(table.createdAt, table.responseStatus),
  index('mcp_audit_logs_client_type_idx').on(table.clientType),
  index('mcp_audit_logs_session_id_idx').on(table.sessionId),
])

export type McpAuditLogRecord = typeof mcpAuditLogs.$inferSelect
export type NewMcpAuditLogRecord = typeof mcpAuditLogs.$inferInsert

// Relations for MCP audit logs
export const mcpAuditLogsRelations = relations(mcpAuditLogs, ({ one }) => ({
  accessToken: one(oauthAccessTokens, {
    fields: [mcpAuditLogs.accessTokenId],
    references: [oauthAccessTokens.id],
  }),
}))

// ============================================
// MCP Sessions Table (Session Conversation Tracking)
// ============================================

/** Session lifecycle status */
export const sessionStatusEnum = pgEnum('session_status', ['active', 'finalized'])

/**
 * MCP session tracking for conversation-level analytics
 *
 * Aggregates per-session activity from individual audit log entries.
 * Enables user journey analysis: search → view → deploy funnel.
 */
export const mcpSessions = pgTable('mcp_sessions', {
  sessionId: text('session_id').primaryKey(),

  // User identification
  userId: text('user_id').references(() => users.id, { onDelete: 'set null' }),
  accessTokenId: text('access_token_id').references(() => oauthAccessTokens.id, { onDelete: 'set null' }),

  // Client metadata
  clientType: text('client_type'),
  clientName: text('client_name'),
  clientVersion: text('client_version'),
  ipHash: text('ip_hash'),

  // Timing
  startedAt: timestamp('started_at', { withTimezone: true }).notNull(),
  lastActivityAt: timestamp('last_activity_at', { withTimezone: true }).notNull(),
  /** Computed on finalization: lastActivityAt - startedAt in seconds */
  durationSeconds: integer('duration_seconds'),

  // Activity counters
  totalRequests: integer('total_requests').notNull().default(0),
  successCount: integer('success_count').notNull().default(0),
  errorCount: integer('error_count').notNull().default(0),

  /** Per-tool call counts e.g. { "semantic_search": 5, "get_plugin_content": 3 } */
  toolCounts: jsonb('tool_counts').$type<Record<string, number>>().notNull().default({}),

  /** Chronological action log (capped at 100 entries) */
  actionLog: jsonb('action_log').$type<Array<{
    action: 'search' | 'view' | 'deploy' | 'suggest' | 'other'
    skillId?: string
    query?: string
    timestamp: string
  }>>().notNull().default([]),

  /** Per-skill interaction counters e.g. { "code-reviewer": { searched: 1, viewed: 2, deployed: 0 } } */
  skillInteractions: jsonb('skill_interactions').$type<Record<string, {
    searched: number; viewed: number; deployed: number
  }>>().notNull().default({}),

  /** Client-reported context merged from report_session_event tool */
  clientContext: jsonb('client_context').$type<{
    promptCount?: number
    suggestionsShown?: number
    suggestionsUsed?: number
    skippedSearches?: number
    sessionEndReason?: string
    pluginVersion?: string
  }>(),

  // Boolean activity flags
  hadSearch: boolean('had_search').notNull().default(false),
  hadView: boolean('had_view').notNull().default(false),
  hadDeployment: boolean('had_deployment').notNull().default(false),

  // Conversion metrics (computed on finalization)
  searchToViewConversion: boolean('search_to_view_conversion'),
  viewToDeployConversion: boolean('view_to_deploy_conversion'),
  avgResponseTime: integer('avg_response_time'),

  // Lifecycle
  status: sessionStatusEnum('status').notNull().default('active'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
}, (table) => [
  index('mcp_sessions_user_id_idx').on(table.userId),
  index('mcp_sessions_started_at_idx').on(table.startedAt),
  index('mcp_sessions_last_activity_idx').on(table.lastActivityAt),
  index('mcp_sessions_status_idx').on(table.status),
  index('mcp_sessions_client_type_idx').on(table.clientType),
  index('mcp_sessions_had_deployment_idx').on(table.hadDeployment),
])

export type McpSessionRecord = typeof mcpSessions.$inferSelect
export type NewMcpSessionRecord = typeof mcpSessions.$inferInsert

/** Relations for MCP sessions */
export const mcpSessionsRelations = relations(mcpSessions, ({ one }) => ({
  user: one(users, {
    fields: [mcpSessions.userId],
    references: [users.id],
  }),
  accessToken: one(oauthAccessTokens, {
    fields: [mcpSessions.accessTokenId],
    references: [oauthAccessTokens.id],
  }),
}))

// ============================================
// Suggestions Table (Collaboration)
// ============================================

/**
 * @deprecated 2026-05-18 — Suggest feature removed (EDU-7987 D2).
 * Table retained for 1 month; drop in a separate migration PR.
 * Do not write new rows. Reads only for historical inspection.
 */
export const suggestions = pgTable('suggestions', {
  id: text('id').primaryKey().$defaultFn(() => crypto.randomUUID()),
  pluginId: text('plugin_id').notNull().references(() => catalogItems.id, { onDelete: 'cascade' }),
  
  title: text('title').notNull(),
  description: text('description').notNull(),
  diff: text('diff'),
  
  status: suggestionStatusEnum('status').notNull().default('pending'),
  
  suggestedBy: text('suggested_by').references(() => users.id, { onDelete: 'set null' }),
  suggestedByName: text('suggested_by_name'),
  
  resolvedBy: text('resolved_by').references(() => users.id, { onDelete: 'set null' }),
  resolvedAt: timestamp('resolved_at', { withTimezone: true }),
  resolveComment: text('resolve_comment'),
  
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
}, (table) => [
  index('suggestions_plugin_id_idx').on(table.pluginId),
  index('suggestions_status_idx').on(table.status),
  index('suggestions_suggested_by_idx').on(table.suggestedBy),
  index('suggestions_created_at_idx').on(table.createdAt),
])

export type SuggestionRecord = typeof suggestions.$inferSelect
export type NewSuggestionRecord = typeof suggestions.$inferInsert

// ============================================
// Skill Events Table (Normalized Skill Usage Tracking)
// ============================================

/** Skill interaction action types */
export const skillEventActionEnum = pgEnum('skill_event_action', [
  'search',           // semantic_search에서 결과로 노출
  'load',             // get_plugin_content로 상세 로드
  'apply',            // report_skill_outcome(applied=true)
  'skip',             // report_search_skip 또는 report_skill_outcome(applied=false)
  'deploy',           // deploy_skill 호출
  'suggest',          // suggest_improvement 호출
  'exercise_search',  // 실습 생성 시 스킬/도구 탐색
  'exercise_apply',   // 생성된 실습을 사용자가 실행
])

/**
 * Normalized skill usage events
 *
 * Replaces JSONB fields (skillInteractions, actionLog) with queryable rows.
 * Each row = one skill interaction within a session.
 * Enables: funnel analysis, skill popularity trends, search→load→apply conversion.
 */
export const skillEvents = pgTable('skill_events', {
  id: text('id').primaryKey().$defaultFn(() => crypto.randomUUID()),
  sessionId: text('session_id').notNull().references(() => mcpSessions.sessionId, { onDelete: 'cascade' }),
  userId: text('user_id').references(() => users.id, { onDelete: 'set null' }),
  skillId: text('skill_id').notNull(),

  /** Interaction type */
  action: skillEventActionEnum('action').notNull(),

  /** Why this skill was used/skipped (free text from client or inferred) */
  context: text('context'),

  /** Search query that surfaced this skill (for search action) */
  query: text('query'),

  /** Position in search results (1-based) */
  rank: integer('rank'),

  /** Relevance score from search */
  score: real('score'),

  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  index('skill_events_session_id_idx').on(table.sessionId),
  index('skill_events_skill_id_idx').on(table.skillId),
  index('skill_events_action_idx').on(table.action),
  index('skill_events_user_id_idx').on(table.userId),
  index('skill_events_created_at_idx').on(table.createdAt),
  index('skill_events_skill_action_idx').on(table.skillId, table.action),
])

export type SkillEventRecord = typeof skillEvents.$inferSelect
export type NewSkillEventRecord = typeof skillEvents.$inferInsert

/** Relations for skill events */
export const skillEventsRelations = relations(skillEvents, ({ one }) => ({
  session: one(mcpSessions, {
    fields: [skillEvents.sessionId],
    references: [mcpSessions.sessionId],
  }),
  user: one(users, {
    fields: [skillEvents.userId],
    references: [users.id],
  }),
}))

export const suggestionsRelations = relations(suggestions, ({ one }) => ({
  plugin: one(catalogItems, {
    fields: [suggestions.pluginId],
    references: [catalogItems.id],
  }),
  suggestedByUser: one(users, {
    fields: [suggestions.suggestedBy],
    references: [users.id],
    relationName: 'suggestedBy',
  }),
  resolvedByUser: one(users, {
    fields: [suggestions.resolvedBy],
    references: [users.id],
    relationName: 'resolvedBy',
  }),
}))

// ============================================
// EvoSkill Tables (Automated Skill Evolution)
// ============================================

/** EvoSkill failure pattern types */
export const evoPatternTypeEnum = pgEnum('evo_pattern_type', [
  'zero_result_cluster',
  'low_conversion',
  'repeated_skip',
])

/** EvoSkill pattern severity levels */
export const evoSeverityEnum = pgEnum('evo_severity', ['low', 'medium', 'high'])

/** EvoSkill pattern processing status */
export const evoPatternStatusEnum = pgEnum('evo_pattern_status', [
  'pending',
  'processing',
  'resolved',
  'dismissed',
  'failed',
])

/** EvoSkill run types */
export const evoRunTypeEnum = pgEnum('evo_run_type', ['analyze', 'generate', 'promote'])

/**
 * Detected failure patterns from skill usage analytics.
 *
 * Populated by the evo-analyze cron job. Each row represents a
 * cluster of related failure signals (zero-result queries, low
 * conversion skills, or repeatedly skipped skills).
 */
export const evoFailurePatterns = pgTable('evo_failure_patterns', {
  id: text('id').primaryKey().$defaultFn(() => crypto.randomUUID()),
  patternType: evoPatternTypeEnum('pattern_type').notNull(),
  /** Pattern-specific detail data (queries, skillId, metrics, etc.) */
  signalData: jsonb('signal_data').$type<Record<string, unknown>>().notNull().default({}),
  severity: evoSeverityEnum('severity').notNull().default('low'),
  status: evoPatternStatusEnum('status').notNull().default('pending'),
  /** Action taken when resolved (e.g., 'skill_created', 'suggestion_filed', 'dismissed') */
  resolvedAction: text('resolved_action'),
  /** ID of the catalog item or suggestion created to resolve this pattern */
  resolvedItemId: text('resolved_item_id'),
  /** Retry attempts used by the generate agent before giving up */
  retryCount: integer('retry_count').notNull().default(0),
  /** Last error message recorded when generation was skipped/failed */
  lastError: text('last_error'),
  analyzedAt: timestamp('analyzed_at', { withTimezone: true }).defaultNow(),
  resolvedAt: timestamp('resolved_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
}, (table) => [
  index('evo_failure_patterns_status_idx').on(table.status),
  index('evo_failure_patterns_type_idx').on(table.patternType),
  index('evo_failure_patterns_severity_idx').on(table.severity),
  index('evo_failure_patterns_created_at_idx').on(table.createdAt),
])

export type EvoFailurePatternRecord = typeof evoFailurePatterns.$inferSelect
export type NewEvoFailurePatternRecord = typeof evoFailurePatterns.$inferInsert

// ============================================
// AI Model Docs Table (EDU-6875: Context Hub 모델 문서 관리)
// ============================================

/** AI provider enum for model docs */
export const aiProviderEnum = pgEnum('ai_provider', ['anthropic', 'google', 'openai'])

/** Sync status for model docs */
export const syncStatusEnum = pgEnum('sync_status', ['success', 'partial', 'failed'])

/**
 * AI model documentation synced from official sources.
 *
 * Stores per-provider model mapping tables (latest models, API IDs, deprecated list)
 * for consumption by Rona and other services via the /api/models endpoint.
 */
export const aiModelDocs = pgTable('ai_model_docs', {
  id: text('id').primaryKey().$defaultFn(() => crypto.randomUUID()),
  /** AI provider (anthropic, google, openai) */
  provider: aiProviderEnum('provider').notNull().unique(),
  /** Structured model data [{name, apiId, deprecated, recommended}] */
  models: jsonb('models').$type<Array<{
    name: string
    apiId: string
    deprecated: boolean
    recommended: boolean
  }>>().notNull().default([]),
  /** Latest models display string (e.g., "Opus 4.6, Sonnet 4.6, Haiku 4.5") */
  latestModels: text('latest_models'),
  /** API model IDs display string (e.g., "claude-opus-4-6, claude-sonnet-4-6") */
  apiIds: text('api_ids'),
  /** Deprecated model patterns display string (e.g., "~~3.5~~, ~~3~~") */
  deprecatedPatterns: text('deprecated_patterns'),
  /** SDK version if applicable */
  sdkVersion: text('sdk_version'),
  /** Date of last official update (from source) */
  updatedOn: text('updated_on'),
  /** Raw content from documentation source (model page) */
  rawContent: text('raw_content'),
  /** SHA-256 hash of rawContent for change detection */
  contentHash: text('content_hash'),
  /** SDK documentation markdown (install, API patterns, error handling) */
  sdkDocs: text('sdk_docs'),
  /** SHA-256 hash of sdkDocs for change detection */
  sdkDocsHash: text('sdk_docs_hash'),
  /** Last successful sync timestamp */
  lastSyncedAt: timestamp('last_synced_at', { withTimezone: true }),
  /** Status of last sync attempt */
  syncStatus: syncStatusEnum('sync_status').default('success'),
  /** Error message if sync failed */
  syncError: text('sync_error'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
}, (table) => [
  index('ai_model_docs_provider_idx').on(table.provider),
  index('ai_model_docs_last_synced_at_idx').on(table.lastSyncedAt),
])

export type AiModelDocRecord = typeof aiModelDocs.$inferSelect
export type NewAiModelDocRecord = typeof aiModelDocs.$inferInsert

/**
 * Audit log for EvoSkill cron runs (analyze, generate, promote).
 *
 * Each row records one execution of an evo cron job, including
 * timing, outcomes, and any errors encountered.
 */
export const evoRunLogs = pgTable('evo_run_logs', {
  id: text('id').primaryKey().$defaultFn(() => crypto.randomUUID()),
  runType: evoRunTypeEnum('run_type').notNull(),
  startedAt: timestamp('started_at', { withTimezone: true }).notNull(),
  completedAt: timestamp('completed_at', { withTimezone: true }),
  /** Run outcome stats, e.g. { patternsFound: 5, skillsCreated: 2, errors: 0 } */
  stats: jsonb('stats').$type<Record<string, number>>().notNull().default({}),
  error: text('error'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
}, (table) => [
  index('evo_run_logs_run_type_idx').on(table.runType),
  index('evo_run_logs_started_at_idx').on(table.startedAt),
])

// ============================================
// AX Dashboard
// ============================================

export const axBillingCycleEnum = pgEnum('ax_billing_cycle', ['monthly', 'yearly'])
export const axSubscriptionStatusEnum = pgEnum('ax_subscription_status', ['active', 'canceled'])

/**
 * 팀원별 구독 현황 (AX 대시보드)
 *
 * 결제내역 트래커 시트가 SSOT이고, 이 테이블은 대시보드가 읽는 사본이다.
 * `pnpm --filter @gpters/db exec tsx scripts/import-ax-subscriptions.ts <csv>` 로 갱신한다.
 *
 * 개인 식별 데이터(ownerName/payer)를 담으므로 API는 관리자에게만 행 단위로 내려주고,
 * 일반 조직 구성원에게는 벤더별 집계만 노출한다.
 */
export const axSubscriptions = pgTable('ax_subscriptions', {
  id: text('id').primaryKey().$defaultFn(() => crypto.randomUUID()),
  /** 서비스 제공자 (예: Anthropic, OpenAI) */
  vendor: text('vendor').notNull(),
  /** 플랜명 (예: Max20x, Pro) */
  plan: text('plan').notNull(),
  /** 좌석 사용자 이름. 팀 공용 구독이면 null */
  ownerName: text('owner_name'),
  /** 매월 결제일 (1~31). 같은 사람이 같은 플랜을 둘 이상 쓰는 경우를 가르는 값이기도 하다 */
  renewalDay: integer('renewal_day'),
  /** 결제 주체 ("본인" 또는 대신 결제하는 사람 이름) */
  payer: text('payer'),
  /**
   * 청구 금액 (통화 단위 그대로. 환율 환산은 하지 않는다)
   *
   * float가 아니라 numeric이다 — 연 단위 원화 청구액은 float32 정밀도(약 1,677만)를
   * 넘어서 금액이 틀어진다. 드라이버가 문자열로 주므로 읽는 쪽에서 숫자로 바꾼다.
   */
  amount: numeric('amount', { precision: 14, scale: 2 }).notNull(),
  currency: text('currency').notNull().default('KRW'),
  billingCycle: axBillingCycleEnum('billing_cycle').notNull().default('monthly'),
  status: axSubscriptionStatusEnum('status').notNull().default('active'),
  note: text('note'),
  /** 마지막 import 시각 */
  syncedAt: timestamp('synced_at', { withTimezone: true }).defaultNow().notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
}, (table) => [
  index('ax_subscriptions_vendor_idx').on(table.vendor),
  index('ax_subscriptions_status_idx').on(table.status),
  index('ax_subscriptions_owner_name_idx').on(table.ownerName),
])

export type AxSubscriptionRecord = typeof axSubscriptions.$inferSelect
export type NewAxSubscriptionRecord = typeof axSubscriptions.$inferInsert

/** AI 코딩 클라이언트 종류 */
export const axUsageClientEnum = pgEnum('ax_usage_client', ['claude-code', 'codex'])

/**
 * 팀원별 AI 클라이언트 사용량 (수집기가 각자 로컬에서 보낸 집계)
 *
 * 원본은 각 팀원 머신의 트랜스크립트다. 서버는 집계 결과만 받는다 —
 * 대화 내용도, 인증 토큰도 넘어오지 않는다.
 */
export const axClientUsage = pgTable('ax_client_usage', {
  id: text('id').primaryKey().$defaultFn(() => crypto.randomUUID()),
  /** 인증 사용자 식별자. memberName은 표시용 스냅샷으로만 유지한다 */
  userId: text('user_id').references(() => users.id, { onDelete: 'set null' }),
  /** 팀원 이름. ax_subscriptions.owner_name과 같은 표기를 쓴다 */
  memberName: text('member_name').notNull(),
  client: axUsageClientEnum('client').notNull(),
  /** 클라이언트가 보고한 원시 티어 문자열 (예: default_claude_max_20x, prolite) */
  planRaw: text('plan_raw'),
  /** 사람이 읽는 플랜명 */
  plan: text('plan'),
  periodStart: timestamp('period_start', { withTimezone: true }).notNull(),
  periodEnd: timestamp('period_end', { withTimezone: true }).notNull(),
  /**
   * 토큰 수는 bigint다 — 주간 캐시 읽기만으로 40억을 넘어 integer(21억)를 넘긴다.
   * mode:'number'로 받는다. 2^53까지는 JS number가 정확하므로 이 규모에서는 안전하다.
   */
  inputTokens: bigint('input_tokens', { mode: 'number' }).notNull().default(0),
  outputTokens: bigint('output_tokens', { mode: 'number' }).notNull().default(0),
  cachedTokens: bigint('cached_tokens', { mode: 'number' }).notNull().default(0),
  sessions: integer('sessions').notNull().default(0),
  /** 모델명 → 토큰 수 */
  models: jsonb('models').$type<Record<string, number>>().default({}),
  /**
   * 주간 한도 사용률.
   *
   * nullable인 게 핵심이다 — Claude Code는 한도 정보를 로컬에 남기지 않아
   * 값이 존재하지 않는다. 0으로 채우면 "한도를 안 쓴 사람"과 구분되지 않는다.
   */
  limitUsedPercent: numeric('limit_used_percent', { precision: 5, scale: 2 }),
  limitResetsAt: timestamp('limit_resets_at', { withTimezone: true }),
  /** 마지막 수집 시각 */
  syncedAt: timestamp('synced_at', { withTimezone: true }).defaultNow().notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
}, (table) => [
  index('ax_client_usage_member_idx').on(table.memberName),
  index('ax_client_usage_user_idx').on(table.userId),
  index('ax_client_usage_client_idx').on(table.client),
  index('ax_client_usage_period_idx').on(table.periodStart),
  uniqueIndex('ax_client_usage_user_client_period_uidx')
    .on(table.userId, table.client, table.periodStart)
    .where(sql`${table.userId} is not null`),
])

export type AxClientUsageRecord = typeof axClientUsage.$inferSelect
export type NewAxClientUsageRecord = typeof axClientUsage.$inferInsert

/**
 * 사용자별 사용량 수집기 마지막 점검 상태
 *
 * 사용량 레코드가 0건이어도 이 행은 갱신된다. 따라서 "도구를 쓰지 않음"과
 * "수집기가 설치되지 않았거나 보고하지 못함"을 서버에서 구분할 수 있다.
 */
export const axUsageCollectorState = pgTable('ax_usage_collector_state', {
  userId: text('user_id')
    .primaryKey()
    .references(() => users.id, { onDelete: 'cascade' }),
  /** 보고 시점의 표시명. 사용자 목록 렌더링과 감사 로그에만 사용한다 */
  memberName: text('member_name').notNull(),
  /** 이번 점검에서 실제 사용량 레코드가 발견된 클라이언트 */
  clients: jsonb('clients').$type<Array<'claude-code' | 'codex'>>().notNull().default([]),
  /** 이번 점검에서 받은 레코드 수. 0이면 수집기는 정상이나 최근 사용량이 없다는 뜻 */
  recordCount: integer('record_count').notNull().default(0),
  lastReportedAt: timestamp('last_reported_at', { withTimezone: true }).defaultNow().notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
}, (table) => [
  index('ax_usage_collector_state_last_reported_idx').on(table.lastReportedAt),
])

export type AxUsageCollectorStateRecord = typeof axUsageCollectorState.$inferSelect
export type NewAxUsageCollectorStateRecord = typeof axUsageCollectorState.$inferInsert

/** 검증 가능한 스킬 실행 결과 — 기존 apply/skip 자기보고와 분리한다 */
export const axExecutionSourceEnum = pgEnum('ax_execution_source', ['aitk', 'bbopters-shared'])
export const axExecutionStatusEnum = pgEnum('ax_execution_status', [
  'running',
  'success',
  'partial',
  'failed',
  'abandoned',
])
export const axExecutionFailureStageEnum = pgEnum('ax_execution_failure_stage', [
  'load',
  'instruction',
  'dependency',
  'execution',
  'validation',
])
export const axExecutionValidationMethodEnum = pgEnum('ax_execution_validation_method', [
  'test',
  'command',
  'artifact',
  'user_confirmation',
  'none',
])
export const axExecutionEventPhaseEnum = pgEnum('ax_execution_event_phase', ['started', 'completed'])

export const axSkillExecutionAttempts = pgTable('ax_skill_execution_attempts', {
  attemptId: text('attempt_id').primaryKey(),
  eventId: text('event_id').notNull().unique(),
  sessionId: text('session_id')
    .notNull()
    .references(() => mcpSessions.sessionId, { onDelete: 'cascade' }),
  userId: text('user_id').references(() => users.id, { onDelete: 'set null' }),
  source: axExecutionSourceEnum('source').notNull(),
  skillId: text('skill_id').notNull(),
  skillVersion: text('skill_version'),
  agent: text('agent').notNull(),
  agentId: text('agent_id').notNull(),
  status: axExecutionStatusEnum('status').notNull(),
  failureStage: axExecutionFailureStageEnum('failure_stage'),
  errorCode: text('error_code'),
  validationMethod: axExecutionValidationMethodEnum('validation_method').notNull().default('none'),
  validationPassed: boolean('validation_passed'),
  validationSummary: text('validation_summary'),
  userAccepted: boolean('user_accepted'),
  occurredAt: timestamp('occurred_at', { withTimezone: true }).notNull(),
  startObserved: boolean('start_observed').notNull().default(false),
  startedAt: timestamp('started_at', { withTimezone: true }).notNull(),
  completedAt: timestamp('completed_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
}, (table) => [
  index('ax_skill_execution_attempts_skill_idx').on(table.skillId),
  index('ax_skill_execution_attempts_user_idx').on(table.userId),
  index('ax_skill_execution_attempts_occurred_idx').on(table.occurredAt),
  index('ax_skill_execution_attempts_status_idx').on(table.status),
  index('ax_skill_execution_attempts_agent_id_idx').on(table.agentId),
  index('ax_skill_execution_attempts_started_at_idx').on(table.startedAt),
  index('ax_skill_execution_attempts_completed_at_idx').on(table.completedAt),
])

export const axSkillExecutionEvents = pgTable('ax_skill_execution_events', {
  eventId: text('event_id').primaryKey(),
  attemptId: text('attempt_id')
    .notNull()
    .references(() => axSkillExecutionAttempts.attemptId, { onDelete: 'cascade' }),
  phase: axExecutionEventPhaseEnum('phase').notNull(),
  occurredAt: timestamp('occurred_at', { withTimezone: true }).notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
}, (table) => [
  index('ax_skill_execution_events_attempt_idx').on(table.attemptId),
])

export type AxSkillExecutionAttemptRecord = typeof axSkillExecutionAttempts.$inferSelect
export type NewAxSkillExecutionAttemptRecord = typeof axSkillExecutionAttempts.$inferInsert
export type AxSkillExecutionEventRecord = typeof axSkillExecutionEvents.$inferSelect
export type NewAxSkillExecutionEventRecord = typeof axSkillExecutionEvents.$inferInsert

/**
 * 에이전트 로컬 트랜스크립트에서 생성한 개인정보 비포함 delta batch.
 *
 * 원문·세션 ID·message ID·cwd·branch·cron 이름은 저장하지 않는다. 이 테이블의
 * executions는 수집기가 명시 보고 이벤트를 몇 건 관측했는지 대조하는 집계값이며,
 * 스킬 실행 성공/실패의 정본을 대신하지 않는다.
 */
export const axAgentTelemetryBatches = pgTable('ax_agent_telemetry_batches', {
  batchId: text('batch_id').primaryKey(),
  schemaVersion: text('schema_version').notNull(),
  agentId: text('agent_id').notNull(),
  collectorInstanceId: text('collector_instance_id').notNull(),
  runtime: jsonb('runtime').$type<{
    openclawVersion: string
    claudeCliVersion: string
    collectorVersion: string
  }>().notNull(),
  windowStart: timestamp('window_start', { withTimezone: true }).notNull(),
  windowEnd: timestamp('window_end', { withTimezone: true }).notNull(),
  collectedAt: timestamp('collected_at', { withTimezone: true }).notNull(),
  inputTokens: bigint('input_tokens', { mode: 'number' }).notNull().default(0),
  outputTokens: bigint('output_tokens', { mode: 'number' }).notNull().default(0),
  cacheCreationInputTokens: bigint('cache_creation_input_tokens', { mode: 'number' }).notNull().default(0),
  cacheReadInputTokens: bigint('cache_read_input_tokens', { mode: 'number' }).notNull().default(0),
  thinkingTokens: bigint('thinking_tokens', { mode: 'number' }).notNull().default(0),
  thinkingTokensRelation: text('thinking_tokens_relation').notNull(),
  sessions: integer('sessions').notNull().default(0),
  turns: integer('turns').notNull().default(0),
  models: jsonb('models').$type<Array<Record<string, unknown>>>().notNull().default([]),
  tools: jsonb('tools').$type<Array<Record<string, unknown>>>().notNull().default([]),
  skillLoads: jsonb('skill_loads').$type<Array<Record<string, unknown>>>().notNull().default([]),
  taskCategories: jsonb('task_categories').$type<Array<Record<string, unknown>>>().notNull().default([]),
  executions: jsonb('executions').$type<Array<Record<string, unknown>>>().notNull().default([]),
  collection: jsonb('collection').$type<Record<string, unknown>>().notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  index('ax_agent_telemetry_agent_window_idx').on(table.agentId, table.windowEnd),
  index('ax_agent_telemetry_collected_idx').on(table.collectedAt),
  uniqueIndex('ax_agent_telemetry_collector_window_uidx').on(
    table.agentId,
    table.collectorInstanceId,
    table.windowStart,
    table.windowEnd,
  ),
])

export type AxAgentTelemetryBatchRecord = typeof axAgentTelemetryBatches.$inferSelect
export type NewAxAgentTelemetryBatchRecord = typeof axAgentTelemetryBatches.$inferInsert

/**
 * 설치형 telemetry collector의 credential·freshness 상태.
 *
 * raw credential과 로컬 경로·profile·project scope는 저장하지 않는다. tokenHash는
 * collector 전용 credential의 SHA-256이고, 한 agent/source에는 한 collector만 허용해
 * 겹치는 스케줄러가 같은 사용량을 이중 계상하지 않게 한다.
 */
export const axAgentTelemetryCollectors = pgTable('ax_agent_telemetry_collectors', {
  collectorId: text('collector_id').primaryKey(),
  userId: text('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  agentId: text('agent_id').notNull(),
  source: text('source').notNull(),
  tokenHash: text('token_hash').notNull().unique(),
  intervalSeconds: integer('interval_seconds').notNull().default(21_600),
  isActive: boolean('is_active').notNull().default(true),
  lastSeenAt: timestamp('last_seen_at', { withTimezone: true }),
  lastSuccessAt: timestamp('last_success_at', { withTimezone: true }),
  lastWindowEnd: timestamp('last_window_end', { withTimezone: true }),
  lastBatchId: text('last_batch_id'),
  lastHealthStatus: text('last_health_status'),
  lastHealthWarnings: jsonb('last_health_warnings').$type<string[]>().notNull().default([]),
  lastRecordsRead: integer('last_records_read').notNull().default(0),
  lastParseFailures: integer('last_parse_failures').notNull().default(0),
  revokedAt: timestamp('revoked_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  uniqueIndex('ax_agent_telemetry_collector_agent_source_uidx')
    .on(table.agentId, table.source)
    .where(sql`${table.isActive} = true`),
  index('ax_agent_telemetry_collector_user_idx').on(table.userId),
  index('ax_agent_telemetry_collector_freshness_idx').on(table.lastSuccessAt),
])

export type AxAgentTelemetryCollectorRecord = typeof axAgentTelemetryCollectors.$inferSelect
export type NewAxAgentTelemetryCollectorRecord = typeof axAgentTelemetryCollectors.$inferInsert
